package com.example.tablenow

import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.children
import com.example.tablenow.databinding.ActivityBookingBinding // Generated by View Binding

class BookingActivity : AppCompatActivity() {

    // View Binding instance
    private lateinit var binding: ActivityBookingBinding

    // Keep track of selected views
    private var selectedDateView: TextView? = null
    private var selectedTimeView: Button? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Inflate and set the content view using View Binding
        binding = ActivityBookingBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Set up initial state
        setupInitialSelection()

        // Set up click listeners
        setupDateListeners()
        setupTimeListeners()

        binding.bookNowButton.setOnClickListener {
            // Handle book now logic
            val guests = binding.guestsEditText.text.toString()
            val date = selectedDateView?.text.toString()
            val time = selectedTimeView?.text.toString()

            // Create the intent to navigate to ConfirmationActivity
            val intent = Intent(this, ConfirmationActivity::class.java)

            // Pass the details to the next screen
            intent.putExtra("GUESTS", guests)
            intent.putExtra("DATE", date)
            intent.putExtra("TIME", time)

            // Launch the ConfirmationActivity
            startActivity(intent)
        }
    }

    private fun setupInitialSelection() {
        selectDate(binding.day12)
        selectTime(binding.time2130)
    }

    private fun setupDateListeners() {
        // Iterate over all TextViews in the calendarGrid
        binding.calendarGrid.children.forEach { view ->
            if (view is TextView && view.text.isNotEmpty()) {
                view.setOnClickListener {
                    selectDate(view)
                }
            }
        }
    }

    private fun setupTimeListeners() {
        // Iterate over all Buttons in the FlexboxLayout
        binding.timeButtonLayout.children.forEach { view ->
            if (view is Button) {
                view.setOnClickListener {
                    selectTime(view)
                }
            }
        }
    }

    private fun selectDate(dateView: TextView) {
        // 1. Deselect the old one
        selectedDateView?.let {
            it.background = ContextCompat.getDrawable(this, android.R.color.transparent)
            it.setTextColor(Color.BLACK)
            it.typeface = Typeface.DEFAULT
        }

        // 2. Select the new one
        dateView.background = ContextCompat.getDrawable(this, R.drawable.date_selected_background)
        dateView.setTextColor(Color.WHITE)
        dateView.typeface = Typeface.DEFAULT_BOLD

        // 3. Update the tracking variable
        selectedDateView = dateView
    }

    private fun selectTime(timeButton: Button) {
        // 1. Deselect the old one
        selectedTimeView?.let {
            it.background = ContextCompat.getDrawable(this, R.drawable.time_button_unselected)
            it.setTextColor(Color.BLACK)
        }

        // 2. Select the new one
        timeButton.background = ContextCompat.getDrawable(this, R.drawable.time_button_selected)
        timeButton.setTextColor(Color.WHITE)

        // 3. Update the tracking variable
        selectedTimeView = timeButton
    }
}